"use strict";
let a = 20;
let b = "Hello, TypeScript!";
let c = true;
let d = "This can be any type";
let e = [1, 2, 3, 4, 5];
let f = [1, "Hello"];
let g = { name: "Alice", age: 30 };
let h = null;
let i = undefined;
let j = a - 1;
console.log(a);
console.log(j);
g = { name: 'Babu', age: 27 };
console.log(g);
let s = '45';
let t = "true";
let u = `hello`;
console.log(s);
console.log(t);
console.log(u);
let bool = false;
let bool2 = true;
let bool3 = false;
let bool4 = false;
console.log(bool);
console.log(bool2);
console.log(bool3);
console.log(bool4);
